name: build

on:
  push:
  pull_request:

jobs:
  libraries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Build the solution and run tests
        run: dotnet test GLOptimizer.sln -c Release --nologo
